/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package avr_application.Composants.Bases;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 *
 * @author 362294
 */
public class Rectangle extends javax.swing.JPanel {

    int x,y,width, height;

    public void setColorBack(Color colorBack) {
        this.colorBack = colorBack;
    }

    public void setColorLine(Color colorLine) {
        this.colorLine = colorLine;
    }

    public void setColorFront(Color colorFront) {
        this.colorFront = colorFront;
    }
    Color colorBack;
    Color colorLine;
    Color colorFront;
    
    /**
     * Creates new form Rectangle
     * @param x = Position en X
     * @param y =Postion  en Y
     * @param with = Largeur
     * @param height = hauteur
     */
    public Rectangle(int x,int y,int with, int height) {
        colorBack = colorFront=colorLine = new java.awt.Color(0, 0,0);
        this.x=x;
        this.y=y;
        this.width =with;
        this.height = height;
        initComponents();
    }

    public JPanel affiche(){
        this.setBounds(x+10,y+10,width+10,height+10);
        this.setBackground(colorBack);
        return this;
    }
 
    @Override
    public  void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.setColor(colorFront);
        g.drawRect(x,y,width,height);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
